version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 40s
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "elfin"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 20s
      timeout: 5s
      retries: 10
  mailserver:
    image: bytemark/smtp
    restart: always
    environment:
      RELAY_HOST: smtp.gmail.com
      RELAY_PORT: 587
      RELAY_USERNAME: testsmtpsenderelfin@gmail.com
      RELAY_PASSWORD: senygmvcdmpvwkay
  elfin:
    image: elfin:latest
    depends_on:
      - postgres
      - elasticsearch
    ports:
      - "8080:8080"
  camunda:
    image: camunda/camunda-bpm-platform
    ports:
      - "8081:8080"
volumes:
  elasticsearch-data:
    driver: local
